# Description:
#   Protobufs used in QUIC.

package_group(
    name = "internal",
    packages = [
        "//gfe/cluster_broker/...",
        "//gfe/gfe2/...",
        "//source/common/quic/...",
    ],
)

package(
    default_hdrs_check = "strict",
)

load("//net/proto2/contrib/portable/cc:portable_proto_build_defs.bzl", "portable_proto_library")
