licenses(["notice"])  # Apache 2
  
load(
    "//bazel:envoy_build_system.bzl",
    "envoy_cc_test",
    "envoy_cc_test_library",
    "envoy_package",
)

envoy_package()

envoy_cc_test_library(
    name = "quic_test_impl_lib",
    hdrs = [
        "quic_test_impl.h",
    ],
    deps = [
    ],
)
