# *EXPERIMENTAL* HTTP/2 Endpoint: understands HTTP/2 at a level above decoding and encoding.

# Please put rules in lexical order by name within sections.

package(default_visibility = ["//source/common/quic/http:gfe_quic"])

################################################################################
# Libraries (i.e. production code).

################################################################################
# Tests and test support.
