package_group(
    name = "internal",
    packages = [
        "//gfe/cluster_broker/...",
        "//gfe/gfe2/...",
        "//source/common/quic/...",
        "//net/grpc/internal/...",
    ],
)

package(
    default_testonly = 1,
    default_visibility = ["//source/common/quic/core/crypto/testdata:internal"],
)
