package_group(
    name = "internal",
    packages = [
        "//gfe/cluster_broker/...",
        "//gfe/gfe2/...",
        "//gfe/quic/...",
        "//net/grpc/internal/...",
    ],
)

package(
    default_testonly = 1,
    default_visibility = [":internal"],
)
